const fs = require('fs');
const path = require('path');
const { withDangerousMod, withProjectBuildGradle } = require('expo/config-plugins');

const START = '// @generated by TillLabel: Android PDF renderer stability';
const END = '// @end generated TillLabel Android PDF renderer stability';
const JAVA_START = '        // @generated by TillLabel: instance-level PDFium close guard';
const JAVA_END = '        // @end generated TillLabel instance-level PDFium close guard';
const PDFIUM_VERSION = '1.0.34';
const VIEWER_AAR = 'AndroidPdfViewer-4.0.1-tillnote.aar';
const VIEWER_DEPENDENCY = "    implementation 'com.github.zacharee:AndroidPdfViewer:4.0.1'";
const LOCAL_VIEWER_DEPENDENCY = `    implementation files(rootProject.file('../android-libs/${VIEWER_AAR}'))`;
const VIEWER_ANDROIDX_DEPENDENCY = "    implementation 'androidx.core:core:1.12.0'";

const buildBlock = () => `${START}
allprojects {
    configurations.configureEach {
        resolutionStrategy.force 'io.legere:pdfiumandroid:${PDFIUM_VERSION}'
    }
}
${END}`;

const patchPdfViewSource = source => {
  if (source.includes(JAVA_START)) return source;

  const javaImportAnchor = 'import java.io.IOException;';
  const pdfiumImportAnchor = 'import io.legere.pdfiumandroid.DefaultLogger;';
  const constructorAnchor = '        ConfigKt.setPdfiumConfig(new Config(new DefaultLogger(), AlreadyClosedBehavior.IGNORE));';
  for (const anchor of [javaImportAnchor, pdfiumImportAnchor, constructorAnchor]) {
    if (!source.includes(anchor)) {
      throw new Error(`[TillLabel] Cannot apply Android PDF close guard; react-native-pdf source changed near: ${anchor}`);
    }
  }

  return source
    .replace(javaImportAnchor, `${javaImportAnchor}\nimport java.lang.reflect.Field;`)
    .replace(pdfiumImportAnchor, `${pdfiumImportAnchor}\nimport io.legere.pdfiumandroid.PdfiumCore;`)
    .replace(constructorAnchor, `${constructorAnchor}\n${JAVA_START}\n        try {\n            Field field = PDFView.class.getDeclaredField("pdfiumCore");\n            field.setAccessible(true);\n            field.set(this, new PdfiumCore(context, new Config(new DefaultLogger(), AlreadyClosedBehavior.IGNORE)));\n        } catch (ReflectiveOperationException exception) {\n            throw new IllegalStateException("Unable to configure safe PdfiumCore close behavior", exception);\n        }\n${JAVA_END}`);
};

const withPdfiumCloseGuard = config => withDangerousMod(config, ['android', cfg => {
  const viewerAarPath = path.join(cfg.modRequest.projectRoot, 'android-libs', VIEWER_AAR);
  if (!fs.existsSync(viewerAarPath)) {
    throw new Error(`[TillLabel] Patched Android PDF viewer was not found: android-libs/${VIEWER_AAR}`);
  }

  const pdfBuildGradlePath = path.join(
    cfg.modRequest.projectRoot,
    'node_modules',
    'react-native-pdf',
    'android',
    'build.gradle',
  );
  if (!fs.existsSync(pdfBuildGradlePath)) {
    throw new Error('[TillLabel] react-native-pdf Android Gradle file was not found.');
  }
  const pdfBuildGradle = fs.readFileSync(pdfBuildGradlePath, 'utf8');
  let patchedBuildGradle = pdfBuildGradle;
  if (!patchedBuildGradle.includes(LOCAL_VIEWER_DEPENDENCY)) {
    if (!patchedBuildGradle.includes(VIEWER_DEPENDENCY)) {
      throw new Error('[TillLabel] Cannot substitute patched Android PDF viewer; dependency contract changed.');
    }
    patchedBuildGradle = patchedBuildGradle.replace(VIEWER_DEPENDENCY, LOCAL_VIEWER_DEPENDENCY);
  }
  if (!patchedBuildGradle.includes(VIEWER_ANDROIDX_DEPENDENCY)) {
    patchedBuildGradle = patchedBuildGradle.replace(
      LOCAL_VIEWER_DEPENDENCY,
      `${LOCAL_VIEWER_DEPENDENCY}\n${VIEWER_ANDROIDX_DEPENDENCY}`,
    );
  }
  if (patchedBuildGradle !== pdfBuildGradle) fs.writeFileSync(pdfBuildGradlePath, patchedBuildGradle, 'utf8');

  const pdfViewPath = path.join(
    cfg.modRequest.projectRoot,
    'node_modules',
    'react-native-pdf',
    'android',
    'src',
    'main',
    'java',
    'org',
    'wonday',
    'pdf',
    'PdfView.java',
  );
  if (!fs.existsSync(pdfViewPath)) {
    throw new Error('[TillLabel] react-native-pdf Android source was not found; PDF close guard was not applied.');
  }
  const source = fs.readFileSync(pdfViewPath, 'utf8');
  const patched = patchPdfViewSource(source);
  if (patched !== source) fs.writeFileSync(pdfViewPath, patched, 'utf8');
  return cfg;
}]);

module.exports = function withPdfiumAndroidVersion(config) {
  const withPinnedPdfium = withProjectBuildGradle(config, cfg => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('[TillLabel] Android PDF renderer stability requires a Groovy project build file.');
    }

    const blockPattern = new RegExp(`${START}[\\s\\S]*?${END}`, 'g');
    const withoutPreviousBlock = cfg.modResults.contents.replace(blockPattern, '').trimEnd();
    cfg.modResults.contents = `${withoutPreviousBlock}\n\n${buildBlock()}\n`;
    return cfg;
  });
  return withPdfiumCloseGuard(withPinnedPdfium);
};

module.exports.PDFIUM_VERSION = PDFIUM_VERSION;
module.exports.patchPdfViewSource = patchPdfViewSource;
