/**
 * genFontMetrics.mjs — extract advance widths from the bundled label fonts so the label engine can
 * measure text without a DOM (deterministic line wrapping and size fitting).
 * Output: src/modules/labels/engine/fontMetrics.generated.ts. Regenerate after changing fonts:
 *   node scripts/genFontMetrics.mjs
 */
import fs from 'fs';
import path from 'path';

const FONTS = {
  latinRegular: 'node_modules/@expo-google-fonts/ibm-plex-sans/400Regular/IBMPlexSans_400Regular.ttf',
  latinBold: 'node_modules/@expo-google-fonts/ibm-plex-sans/700Bold/IBMPlexSans_700Bold.ttf',
  arabicRegular: 'node_modules/@expo-google-fonts/ibm-plex-sans-arabic/400Regular/IBMPlexSansArabic_400Regular.ttf',
  arabicBold: 'node_modules/@expo-google-fonts/ibm-plex-sans-arabic/700Bold/IBMPlexSansArabic_700Bold.ttf',
};

function tables(buf) {
  const n = buf.readUInt16BE(4); const t = {};
  for (let i = 0; i < n; i++) { const r = 12 + i * 16; t[buf.toString('ascii', r, r + 4)] = buf.readUInt32BE(r + 8); }
  return t;
}
function cmap(buf, off) {
  const map = new Map(); const nt = buf.readUInt16BE(off + 2);
  for (let i = 0; i < nt; i++) {
    const so = off + buf.readUInt32BE(off + 4 + i * 8 + 4); const f = buf.readUInt16BE(so);
    if (f === 4) {
      const sc = buf.readUInt16BE(so + 6) / 2; const ends = so + 14, starts = ends + sc * 2 + 2, deltas = starts + sc * 2, ranges = deltas + sc * 2;
      for (let j = 0; j < sc; j++) {
        const e = buf.readUInt16BE(ends + j * 2), s = buf.readUInt16BE(starts + j * 2), d = buf.readInt16BE(deltas + j * 2), ro = buf.readUInt16BE(ranges + j * 2);
        for (let c = s; c <= e && c !== 0xffff; c++) {
          let g;
          if (ro === 0) g = (c + d) & 0xffff;
          else { const ga = ranges + j * 2 + ro + (c - s) * 2; g = buf.readUInt16BE(ga); if (g) g = (g + d) & 0xffff; }
          if (g && !map.has(c)) map.set(c, g);
        }
      }
    } else if (f === 12) {
      const ng = buf.readUInt32BE(so + 12);
      for (let j = 0; j < ng; j++) { const s = buf.readUInt32BE(so + 16 + j * 12), e = buf.readUInt32BE(so + 20 + j * 12), g0 = buf.readUInt32BE(so + 24 + j * 12); for (let c = s; c <= e; c++) if (!map.has(c)) map.set(c, g0 + (c - s)); }
    }
  }
  return map;
}
function metrics(file) {
  const buf = fs.readFileSync(file); const t = tables(buf);
  const unitsPerEm = buf.readUInt16BE(t.head + 18);
  const numH = buf.readUInt16BE(t.hhea + 34);
  const adv = g => buf.readUInt16BE(t.hmtx + Math.min(g, numH - 1) * 4);
  const out = {};
  for (const [cp, g] of cmap(buf, t.cmap)) {
    const keep = (cp >= 0x20 && cp <= 0x24f) || (cp >= 0x600 && cp <= 0x6ff) || (cp >= 0x2000 && cp <= 0x20cf) || (cp >= 0xfb50 && cp <= 0xfeff) || cp === 0xa0;
    if (keep) out[cp] = Math.round((adv(g) / unitsPerEm) * 1000);
  }
  return out;
}
const result = {};
for (const [k, f] of Object.entries(FONTS)) result[k] = metrics(f);
const body = `// AUTO-GENERATED by scripts/genFontMetrics.mjs — advance widths in 1/1000 em. Do not hand-edit.
// Fonts: IBM Plex Sans / IBM Plex Sans Arabic (SIL OFL 1.1), from @expo-google-fonts.
export const FONT_METRICS: Record<'latinRegular' | 'latinBold' | 'arabicRegular' | 'arabicBold', Record<number, number>> = ${JSON.stringify(result)};
`;
fs.writeFileSync(path.join('src/modules/labels/engine/fontMetrics.generated.ts'), body);
console.log(Object.entries(result).map(([k, v]) => `${k}: ${Object.keys(v).length} glyphs`).join(', '), `(${body.length} bytes)`);
